import type { Lang } from './config';

const es = {
  idioma: 'Español',
  idiomaCorto: 'ES',
  cambiarIdioma: 'Versió en valencià',
  inicio: 'Inicio',
  saltar: 'Saltar al contenido',
  menu: 'Menú',
  explorar: 'Explorar la guía',
  verGuia: 'Ver la guía',
  verSeccion: 'Ver toda la sección',
  guias: 'guías',
  guia: 'guía',
  fotos: 'fotografías',
  publicadoEn: 'Publicado originalmente en',
  textosDe: 'Textos',
  fotosDe: 'Fotografías',
  anterior: 'Anterior',
  siguiente: 'Siguiente',
  enEstaGuia: 'En esta guía',
  masEnSeccion: 'Más en',
  catalogo: 'Catálogo de flores',
  todasFamilias: 'Todas las familias',
  familia: 'Familia',
  buscar: 'Buscar por nombre',
  buscarAyuda: 'Nombre científico o común',
  resultados: (n: number) => (n === 1 ? '1 flor' : `${n} flores`),
  sinResultados: 'Ninguna flor coincide con la búsqueda.',
  letras: 'Ir a la letra',
  ampliar: 'Ampliar la fotografía',
  cerrar: 'Cerrar',
  estaciones: 'Las cuatro estaciones',
  estacionesTexto: 'La rambla cambia de color cada tres meses. Un paseo por el año.',
  descubre: 'Para empezar',
  descubreTexto: 'Algunas de las guías más queridas del blog original.',
  homenaje: 'Francisca y Tadeo',
  homenajeTexto:
    'Este sitio recoge el trabajo de dos hermanos de Cinctorres que, ya jubilados, recorrieron durante años las montañas dels Ports con una cámara y un cuaderno. Ella escribía; él fotografiaba.',
  homenajeEnlace: 'Conocer a los autores',
  portadaCta: 'Explorar la guía',
  portadaCta2: 'Los autores',
  cifras: (guias: number, fotos: number) => `${guias} guías · ${fotos} fotografías · 2014–2016`,
  pieTextos: 'Textos de Francisca Julián Querol y fotografías de Tadeo Julián Querol.',
  pieNota: 'Sitio sin publicidad, sin cookies y sin ánimo de lucro, dedicado al patrimonio natural de Cinctorres y de la comarca dels Ports.',
  codigo: 'Código fuente',
  hermano: 'Proyecto hermano',
  noEncontrada: 'Página no encontrada',
  noEncontradaTexto: 'La dirección que buscas no existe o cambió al renovar el sitio.',
  volverInicio: 'Volver a la portada',
  rss: 'Novedades (RSS)',
};

const ca: typeof es = {
  idioma: 'Valencià',
  idiomaCorto: 'CA',
  cambiarIdioma: 'Versión en castellano',
  inicio: 'Inici',
  saltar: 'Salta al contingut',
  menu: 'Menú',
  explorar: 'Explorar la guia',
  verGuia: 'Veure la guia',
  verSeccion: 'Veure tota la secció',
  guias: 'guies',
  guia: 'guia',
  fotos: 'fotografies',
  publicadoEn: 'Publicat originalment el',
  textosDe: 'Textos',
  fotosDe: 'Fotografies',
  anterior: 'Anterior',
  siguiente: 'Següent',
  enEstaGuia: 'En aquesta guia',
  masEnSeccion: 'Més en',
  catalogo: 'Catàleg de flors',
  todasFamilias: 'Totes les famílies',
  familia: 'Família',
  buscar: 'Buscar per nom',
  buscarAyuda: 'Nom científic o comú',
  resultados: (n: number) => (n === 1 ? '1 flor' : `${n} flors`),
  sinResultados: 'Cap flor coincideix amb la cerca.',
  letras: 'Anar a la lletra',
  ampliar: 'Ampliar la fotografia',
  cerrar: 'Tancar',
  estaciones: 'Les quatre estacions',
  estacionesTexto: 'La rambla canvia de color cada tres mesos. Un passeig per l’any.',
  descubre: 'Per a començar',
  descubreTexto: 'Algunes de les guies més estimades del blog original.',
  homenaje: 'Francisca i Tadeo',
  homenajeTexto:
    'Aquest lloc recull el treball de dos germans de Cinctorres que, ja jubilats, van recórrer durant anys les muntanyes dels Ports amb una càmera i un quadern. Ella escrivia; ell fotografiava.',
  homenajeEnlace: 'Conéixer els autors',
  portadaCta: 'Explorar la guia',
  portadaCta2: 'Els autors',
  cifras: (guias: number, fotos: number) => `${guias} guies · ${fotos} fotografies · 2014–2016`,
  pieTextos: 'Textos de Francisca Julián Querol i fotografies de Tadeo Julián Querol.',
  pieNota: 'Lloc sense publicitat, sense galetes i sense ànim de lucre, dedicat al patrimoni natural de Cinctorres i de la comarca dels Ports.',
  codigo: 'Codi font',
  hermano: 'Projecte germà',
  noEncontrada: 'Pàgina no trobada',
  noEncontradaTexto: 'L’adreça que busques no existeix o va canviar en renovar el lloc.',
  volverInicio: 'Tornar a la portada',
  rss: 'Novetats (RSS)',
};

export const UI: Record<Lang, typeof es> = { es, ca };
export const ui = (lang: Lang) => UI[lang];
