import type { Lang } from './config';

const es = {
  idioma: 'Español',
  idiomaCorto: 'ES',
  idiomaEtiqueta: 'Idioma',
  inicio: 'Inicio',
  marcaSub: 'Ecosistema · Els Ports',
  portadaTitulo: 'Ecosistema de la <i>Rambla Celumbres</i>',
  saltar: 'Saltar al contenido',
  menu: 'Menú',
  explorar: 'Explorar la guía',
  verGuia: 'Ver la guía',
  verSeccion: 'Ver toda la sección',
  guias: 'guías',
  guia: 'guía',
  fotos: 'fotografías',
  publicadoEn: 'Publicado originalmente en',
  textosDe: 'Textos',
  fotosDe: 'Fotografías',
  anterior: 'Anterior',
  siguiente: 'Siguiente',
  enEstaGuia: 'En esta guía',
  masEnSeccion: (seccion: string) => `Más en ${seccion}`,
  catalogo: 'Catálogo de flores',
  todasFamilias: 'Todas las familias',
  familia: 'Familia',
  buscar: 'Buscar por nombre',
  buscarAyuda: 'Nombre científico o común',
  resultados: (n: number) => (n === 1 ? '1 flor' : `${n} flores`),
  sinResultados: 'Ninguna flor coincide con la búsqueda.',
  letras: 'Ir a la letra',
  ampliar: 'Ampliar la fotografía',
  cerrar: 'Cerrar',
  estaciones: 'Las cuatro estaciones',
  estacionesTexto: 'La rambla cambia de color cada tres meses. Un paseo por el año.',
  descubre: 'Para empezar',
  descubreTexto: 'Algunas de las guías más queridas del blog original.',
  laGuia: 'La guía',
  sobreElSitio: 'Sobre el sitio',
  intro: 'Una guía fotográfica de la vida que hay en una rambla que casi nunca lleva agua: <b>flores, insectos, aves, mamíferos, hongos y líquenes</b>, observados durante tres años entre la Roca Parda y la Roca Roja.',
  textosYFotos: 'Textos y fotografías',
  homenaje: 'Tadeo y Paquita',
  homenajeTexto:
    'Este sitio recoge el trabajo de dos hermanos de Cinctorres que, ya jubilados, recorrieron durante años las montañas dels Ports con una cámara y un cuaderno. Ella escribía; él fotografiaba.',
  homenajeEnlace: 'Conocer a los autores',
  portadaCta: 'Explorar la guía',
  portadaCta2: 'Los autores',
  cifras: (guias: number, fotos: number) => `${guias} guías · ${fotos} fotografías · 2014–2016`,
  pieTextos: 'Textos de Francisca Julián Querol y fotografías de Tadeo Julián Querol.',
  pieNota: 'Sitio sin publicidad, sin cookies y sin ánimo de lucro, dedicado al patrimonio natural de Cinctorres y de la comarca dels Ports.',
  codigo: 'Código fuente',
  hermano: 'Proyecto hermano',
  noEncontrada: 'Página no encontrada',
  noEncontradaTexto: 'La dirección que buscas no existe o cambió al renovar el sitio.',
  volverInicio: 'Volver a la portada',
  rss: 'Novedades (RSS)',
};

const ca: typeof es = {
  idioma: 'Valencià',
  idiomaCorto: 'CA',
  idiomaEtiqueta: 'Idioma',
  inicio: 'Inici',
  marcaSub: 'Ecosistema · Els Ports',
  portadaTitulo: 'Ecosistema de la <i>Rambla Celumbres</i>',
  saltar: 'Salta al contingut',
  menu: 'Menú',
  explorar: 'Explorar la guia',
  verGuia: 'Veure la guia',
  verSeccion: 'Veure tota la secció',
  guias: 'guies',
  guia: 'guia',
  fotos: 'fotografies',
  publicadoEn: 'Publicat originalment el',
  textosDe: 'Textos',
  fotosDe: 'Fotografies',
  anterior: 'Anterior',
  siguiente: 'Següent',
  enEstaGuia: 'En aquesta guia',
  masEnSeccion: (seccion: string) => `Més en ${seccion}`,
  catalogo: 'Catàleg de flors',
  todasFamilias: 'Totes les famílies',
  familia: 'Família',
  buscar: 'Buscar per nom',
  buscarAyuda: 'Nom científic o comú',
  resultados: (n: number) => (n === 1 ? '1 flor' : `${n} flors`),
  sinResultados: 'Cap flor coincideix amb la cerca.',
  letras: 'Anar a la lletra',
  ampliar: 'Ampliar la fotografia',
  cerrar: 'Tancar',
  estaciones: 'Les quatre estacions',
  estacionesTexto: 'La rambla canvia de color cada tres mesos. Un passeig per l’any.',
  descubre: 'Per a començar',
  descubreTexto: 'Algunes de les guies més estimades del blog original.',
  laGuia: 'La guia',
  sobreElSitio: 'Sobre el lloc',
  intro: 'Una guia fotogràfica de la vida que hi ha en una rambla que quasi mai porta aigua: <b>flors, insectes, aus, mamífers, fongs i líquens</b>, observats durant tres anys entre la Roca Parda i la Roca Roja.',
  textosYFotos: 'Textos i fotografies',
  homenaje: 'Tadeo i Paquita',
  homenajeTexto:
    'Aquest lloc recull el treball de dos germans de Cinctorres que, ja jubilats, van recórrer durant anys les muntanyes dels Ports amb una càmera i un quadern. Ella escrivia; ell fotografiava.',
  homenajeEnlace: 'Conéixer els autors',
  portadaCta: 'Explorar la guia',
  portadaCta2: 'Els autors',
  cifras: (guias: number, fotos: number) => `${guias} guies · ${fotos} fotografies · 2014–2016`,
  pieTextos: 'Textos de Francisca Julián Querol i fotografies de Tadeo Julián Querol.',
  pieNota: 'Lloc sense publicitat, sense galetes i sense ànim de lucre, dedicat al patrimoni natural de Cinctorres i de la comarca dels Ports.',
  codigo: 'Codi font',
  hermano: 'Projecte germà',
  noEncontrada: 'Pàgina no trobada',
  noEncontradaTexto: 'L’adreça que busques no existeix o va canviar en renovar el lloc.',
  volverInicio: 'Tornar a la portada',
  rss: 'Novetats (RSS)',
};

const en: typeof es = {
  idioma: 'English',
  idiomaCorto: 'EN',
  idiomaEtiqueta: 'Language',
  inicio: 'Home',
  marcaSub: 'Ecosystem · Els Ports',
  portadaTitulo: '<i>Rambla Celumbres</i> Ecosystem',
  saltar: 'Skip to content',
  menu: 'Menu',
  explorar: 'Explore the guide',
  verGuia: 'Read the guide',
  verSeccion: 'See the whole section',
  guias: 'guides',
  guia: 'guide',
  fotos: 'photographs',
  publicadoEn: 'Originally published in',
  textosDe: 'Text',
  fotosDe: 'Photographs',
  anterior: 'Previous',
  siguiente: 'Next',
  enEstaGuia: 'In this guide',
  masEnSeccion: (seccion: string) => `More in ${seccion}`,
  catalogo: 'Wildflower catalogue',
  todasFamilias: 'All families',
  familia: 'Family',
  buscar: 'Search by name',
  buscarAyuda: 'Scientific or common name',
  resultados: (n: number) => (n === 1 ? '1 flower' : `${n} flowers`),
  sinResultados: 'No flower matches your search.',
  letras: 'Jump to letter',
  ampliar: 'Enlarge the photograph',
  cerrar: 'Close',
  estaciones: 'The four seasons',
  estacionesTexto: 'The rambla changes colour every three months. A walk through the year.',
  descubre: 'Where to start',
  descubreTexto: 'Some of the best-loved guides from the original blog.',
  laGuia: 'The guide',
  sobreElSitio: 'About this site',
  intro: 'A photographic guide to the life of a rambla that hardly ever carries water: <b>flowers, insects, birds, mammals, fungi and lichens</b>, observed over three years between the Roca Parda and the Roca Roja.',
  textosYFotos: 'Text and photographs',
  homenaje: 'Tadeo and Paquita',
  homenajeTexto:
    'This site gathers the work of two siblings from Cinctorres who, after retiring, spent years walking the Els Ports mountains with a camera and a notebook. She wrote; he photographed.',
  homenajeEnlace: 'Meet the authors',
  portadaCta: 'Explore the guide',
  portadaCta2: 'The authors',
  cifras: (guias: number, fotos: number) => `${guias} guides · ${fotos} photographs · 2014–2016`,
  pieTextos: 'Text by Francisca Julián Querol and photographs by Tadeo Julián Querol.',
  pieNota: 'A site with no advertising, no cookies and no commercial purpose, devoted to the natural heritage of Cinctorres and the Els Ports region.',
  codigo: 'Source code',
  hermano: 'Sister project',
  noEncontrada: 'Page not found',
  noEncontradaTexto: 'The address you are looking for does not exist or changed when the site was rebuilt.',
  volverInicio: 'Back to the home page',
  rss: 'Updates (RSS)',
};

const zh: typeof es = {
  idioma: '中文',
  idiomaCorto: '中文',
  idiomaEtiqueta: '语言',
  inicio: '首页',
  marcaSub: '生态系统 · Els Ports',
  portadaTitulo: '塞伦布雷斯干河生态系统',
  saltar: '跳到正文',
  menu: '菜单',
  explorar: '浏览图鉴',
  verGuia: '阅读本篇',
  verSeccion: '查看整个栏目',
  guias: '篇',
  guia: '篇',
  fotos: '张照片',
  publicadoEn: '原文发表于',
  textosDe: '文字',
  fotosDe: '摄影',
  anterior: '上一篇',
  siguiente: '下一篇',
  enEstaGuia: '本篇目录',
  masEnSeccion: (seccion: string) => `“${seccion}”栏目更多内容`,
  catalogo: '野花图录',
  todasFamilias: '所有科',
  familia: '科',
  buscar: '按名称查找',
  buscarAyuda: '学名或俗名',
  resultados: (n: number) => `${n} 种花`,
  sinResultados: '没有符合条件的花。',
  letras: '跳到字母',
  ampliar: '放大照片',
  cerrar: '关闭',
  estaciones: '四季',
  estacionesTexto: '干河每三个月换一次颜色。走过一年。',
  descubre: '从这里开始',
  descubreTexto: '原博客中最受喜爱的几篇。',
  laGuia: '图鉴',
  sobreElSitio: '关于本站',
  intro: '一条几乎从不流水的干河里的生命摄影图鉴：<b>花、昆虫、鸟类、哺乳动物、真菌与地衣</b>，三年间在 Roca Parda 与 Roca Roja 之间观察记录。',
  textosYFotos: '文字与摄影',
  homenaje: '塔德奥与帕基塔',
  homenajeTexto:
    '本站汇集了 Cinctorres 一对同胞的作品。退休之后，他们带着相机和笔记本，多年行走于 Els Ports 山区。她写字，他拍照。',
  homenajeEnlace: '认识作者',
  portadaCta: '浏览图鉴',
  portadaCta2: '作者',
  cifras: (guias: number, fotos: number) => `${guias} 篇 · ${fotos} 张照片 · 2014–2016`,
  pieTextos: '文字：Francisca Julián Querol；摄影：Tadeo Julián Querol。',
  pieNota: '本站无广告、无 Cookie、不以营利为目的，献给 Cinctorres 和 Els Ports 地区的自然遗产。',
  codigo: '源代码',
  hermano: '姊妹项目',
  noEncontrada: '页面不存在',
  noEncontradaTexto: '您要找的地址不存在，或在网站改版时已经变更。',
  volverInicio: '返回首页',
  rss: '更新（RSS）',
};

export const UI: Record<Lang, typeof es> = { es, ca, en, zh };
export const ui = (lang: Lang) => UI[lang];
